### ISSUE TITLE
`WalletCollector ListAccountsfailed` kills `lndmon` container

### ISSUE THREAD

**Issue by gcool-info** [lightninglabs/lndmon#84] opened 2022-08-07 14:06 UTC
I have a `docker-compose.yaml` where I'm spinning up `btcd`, `lnd`, `lndmon` and `prometheus` containers.

After running `docker-compose up`, `lndmon` starts but stops with the following error logs:

```
lndmon                     | Lndmon exiting with error: WalletCollector ListAccountsfailed with: rpc error: code = Unknown desc = account default has unsupported key scope m/1017'/1'
lnd                        | 2022-08-07 13:58:30.881 [ERR] RPCS: [/walletrpc.WalletKit/ListAccounts]: account default has unsupported key scope m/1017'/1'
lndmon                     | 2022/08/07 13:58:30 Stopping Prometheus Exporter
lndmon                     | 2022-08-07 13:58:30.883 [INF] HTLC: Stopping Htlc Monitor
lndmon                     | WalletCollector ListAccountsfailed with: rpc error: code = Unknown desc = account default has unsupported key scope m/1017'/1'
lndmon exited with code 1
```

**Some more info**:
- my `lnd` `Dockerfile` is very similar to the [default one](https://github.com/lightningnetwork/lnd/blob/master/Dockerfile)
- running on latest `master`, both for `lnd` and `lndmon`.
- running on `simnet`
- starting `lnd` with `--noseedbackup`

Any help would be massively appreciated :)

**Comment by gcool-info** [comment] 2022-08-07 18:27
**Update**:

The error originates from lnd: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/walletrpc/walletkit_server.go#L1386

I wonder if an error from `lnd` should kill the `lndmon` container? Shouldn't it handle gracefully somehow?

**Comment by bitromortac** [comment] 2022-08-08 07:12
Are you willing to share your `Dockerfile`? I would try to reproduce.

**Comment by bitromortac** [comment] 2022-08-08 12:11
I could reproduce the lnd error on a freshly initialized `simnet`. It is possibly due to a different address derivation for `simnet`. I could run with `regtest` though, would that be a workaround for you? I think the issue should be fixed in lnd, will open an issue.

**Comment by gcool-info** [comment] 2022-08-09 19:41
Thanks for looking into this @bitromortac !

**Closed** 2022-08-09 19:42 UTC
